var theList = [
    "Asthma Kid", 
    "Snausages", 
    "Beautiful Milw", 
    "Holy Aioli",
    "Church on Wheels ", 
    "Food Network After Dark: where Guy Fieri cooks nude and his blinding white chest hair emits an ethereal glow",
    "Soup shooters--tomato bisque! Line em up! Drink til we're dead. Uh sir this is beef stew. We could only fit one chunk of potato in here. Noodles everywhere.",
    "Take me Saint Louis I'm ready for your arch", 
    "I gave birth to the Loch Ness Monster", 
    "Tongue to anus, that's my favorite part",
    "Brain teaser: everyone is DEAD. WHY. Yes or no questions.", 
    "I'm not gonna eat any damn soup!", 
    "___ hosting Pawn Stars: what's this, JFKs cigarette case? It don't have unicorns on it--$2.00!",
    "Sir Bananas Fosters Waffles", 
    "Quarly", 
    "You can't swing a dead cat without hitting a cheese shop.", 
    "Watch the curds, man.", 
    "Bakedbeaninstein",
    "There's nothing like a good hedge maze", 
    "Doodle like a lady.", 
    "'We all think a unicorn sounds cool but how scary would a horse with TWO horns be?' 'Where would the horns be?''Well I was thinking on the top of the head but we can say one in the front and one in the back.'", 
    "Beard theory no. 1: it grows naturally. Theory no. 2: it is powered by the wind!",
    "Final Fantasy. That's different from football...?", 
    "That's a very anatomical violin.", 
    "True science fact: the lamprey is the only known sea creature to regularly feed on lighting fixtures. Hence its name.",
    "Were you thinking about another riddle while you were with my riddle?!", 
    "Is that a heron? No that's a plane.", 
    "He sexed himself to death.",
    "Cream-filled ass puffs.", 
    "Beauty and the Beast 2: 'this is the old office chair and it's gonna sing a song about monogamy!'", 
    "I want to slough your brains out",
    "She was a very rambunctious nun.", 
    "Not today, Columbus", 
    "'The Pulsing Cankles' are releasing a new EP next week featuring the new hit single 'Cank Up The Volume'.", 
    "Oh trust me, I know my way around a bongo.", 
    "Rip Van Douchebags bourbon", 
    "I thought I found a sudafed, but it was a fruit snack.", 
    "Correcttoes",
    "Toeknuckles", 
    "I have 140 people that are personally going to carve out my guts.", 
    "Prostitute Cancer", 
    "I didn't say you WERE a harpy.",
    "Jellyfish are 95 percent water and 5 percent marmalade.", 
    "I SAID 'BIG BANG TICKET'", 
    "Hot crone sounds like a Southern side dish.", 
    "Smothered crone.",
    "'Saw Saw' the murderous panda--you hear the sound of gentle munching for hours but it keeps getting closer.", 
    "Glitter Butt", 
    "Tongue to glitter butt",
    "Do they tattoo the penis proper?", 
    "Throw me in the ground let the worms have me.", 
    "There are only so many clothes you can take off",
    "Remember that time I awkwardly ripped off my pant leg at a staff meeting.",    
    "Yeah well anything should be a globule.", 
    "Okay, time to pull out the chub.",
    "Enough of this muffery!!", 
    "I ravish very gently. It's just a light ravishing.", 
    "You know it's a bad day when you see nuns twerking.",
    "You think it's girls gone wild, but surprise, it's about parks! And that girl, she a baboon!", 
    "What if you had to diffuse a bomb and they were like all different root vegetables and then they were like 'cut the wire with a picture of a parsnip on it.'",
    "I have decided that I am like, really, super into garlic.", 
    "It's beginning to look a lot like space prison!", 
    "Ask me about my cankles!", 
    "Thankels for the cankels.", 
    "Canklenator",
    "Cankles away!", 
    "More grog please.", 
    "Russian nesting doll babies.", 
    "It's the cycle of kangaroo birth.",
    "Come on down for gay member Wednesday!", 
    "I feel like a baby just died in my head.", 
    "I'm totally normal except I have a rabid badger",
    "Did you know that guy from the Humpty Dance lost his nose in a cooking accident?", 
    "Suck light, bats!!", 
    "This is my batfork. With it, I eat my batmeals.",
    "A squid inked in my broth.", 
    "He took off half my nipple, that's for sure.", 
    "Muran is goooone!!!!", 
    "I can't see, my hair is too luscious!!",
    "4:40 on a Friday, my new perfume. It's called 'Exhaustion: by Jared Sage.'", 
    "I don't think I'd marry a bull. Unless it was the right bull.",
    "The streets run red with chili.", 
    "Sometimes potatoes just need to back the fuck off the flavor profile.", 
    "This ain't like those chump hot dog contests where they dip their buns in water.",
    "There was one lady at Panera who accused me personally of putting a twig in her salad.", 
    "No mas weird eyeball.", 
    "Testy pork sample.", 
    "The entire planet is Sarlac poop.",
    "That's why aliens don't come to earth. It's like walking into a sewage treatment plant.", 
    "'Can't you see that I am licking my own eggs?' 'Excuse me?'", 
    "I cardamommed the shit out of this.",
    "I'm gonna do it with a bundt cake.", 
    "I want a hot load.", 
    "Hipster Demon From Hell", 
    "Molten Salt has to be a real person.", 
    "Excuse my slobber teeth",
    "Darles chickens a tale of two titties",    
    "A little bit of Bellatrix on our side...", 
    "Ball on a budget.", 
    "Sunglasses the Hutt", 
    "I sometimes think I want an aquarium but then I remember they're a lot of work and fish kind of bore me.", 
    "To the voice changer!", 
    "Old Pot Pie Harper.",
    "Occasionally when I write 1:30 I think 'one-turdy', and then I laugh.", 
    "'He died of a drug overdose.' 'Well that's not good.'", 
    "It's like the barnacle on the step-child's head.",
    "TARC 2: The Wreckoning", 
    "Just eat a Twinkie and you'll see: they taste like regret.", 
    "Where to recycle batteries? I just take them down to my fireplace!",
    "I don't need to watch TV. I'm playing games and ruminating on my own inadequacies.", 
    "Rotisserie placenta", 
    "Little known fact: when Michelangelo was carving the David, he started with a block of marble three times the size.",
    "As someone who lived in the pacific northwest...", 
    "There's only so much milk.", 
    "I thought it was hamburger helper like 'help me get by in life,' not 'help the hamburger.'",
    "Dr. Dry Bub", 
    "Jennifer, pissed off bride on line three, pissed off bride on line three.", 
    "'Who are you?' 'Someone who loves you.'",
    "I love Hitler THIS much!", 
    "I do love dead-eyed women.", 
    "That'll get your ass trampled.", 
    "If you look into that orangutan's face, it's eyes look very soulless.",
    "Gravy Chute", 
    "Ermagerd DERGANS", 
    "Ermagerd gergeryles!!",
    "I have a deviated vaGINA",
    "If I die, I want you put my ashes into a bullet, and then I want you to put that bullet into the man that killed me.",
    "Your father's tuffet, an elegant weapon for a more civilized age.",
    "I'd probably start writing something I wanted on my body forever. Like 'Dolores Umbridge is a cunt'",
    "Lolly Cocks",
    "POD: Puddle Of Dung",
    "Chicken glutes, $.20 per lb",
    "I like my summers like I like my women: hot and gross.",
    "I don't know how a feather duster can manage to be so sexy but she does.",
    "You should have Ariel catch and stuff a human for retribution.",
    "Obviously we'll have to have a bake sale.",
    "This is a very efficient list. Survival-only. Mostly tissues and medicine. Also speaking of groceries, I ate all of your hard-boiled eggs.",
    "Nostalgic bestiality",
    "I had really normal childhood crushes. I had a crush on Dan Aykroyd.",
    "Yeah of course. People get things bronzed all the time.",
    "Murder ring",
    "That's a minty, minty death",
    "Now that I think about it, I haven't had a period in 27 years.",
    "Hot polyp.",
    "I just don't want it to be 'oh, chubby girl ends up with the hot fat guy.'",
    "This condom's as soluble as cotton candy.",
    "The Copernicus Experience",
    "Heir Sphincter!",
    "Tinder tots",
    "Bitch tits!",
    "Get your vomit on!",
    "What would you like to order, Satan? 'Souls, please!'",
    "'What are you thinking about?' 'I'm thinking about if the rules of relativity still apply if your frame of reference and your observed object are both light.' 'Oh.'",
    "John Waters is my everything.",
    "I have a reference point for outhouse death.",
    "Frick-frack paddy whack",
    "So, if you ever want to be challenged, to a... ROCK-OFF...",
    "Amanadaaaa... Amanada ding dong",
    "Those were the days, the Golden Age of Memes.",
    "If Harry Potter had TWO O's instead of one. That would be funny.",
    "I'm going to be holding meetings in the Happy Climber if anyone wants to see me on something.",
    "uh, I think it's pronounced cah-bahge.",
    "I'm not aaaaall that about the Balkans.",
    "I have no internal timeline of Cher's career.",
    "Ptang ptang biscuit barrel, it's really funny, anyway does anyone know why the adding machine says 94 thousand dollars?",
    "Pocket Mennonite.", 
    "This kid got duct taped to a hammock.",
    "'Do you think tuna from Subway would give me some sort of disease?' 'Who? Did you say Tina? What did you do to Tina?!'",
    "Watch the mummy rap",
    "Di-sex-tion--there were 69 people in attendance.",
    "If you stacked all the Lego bricks on Earth up you could reach Pluto.",
    "These gardening gloves are now +5 protection against poison sumac.",
    "I like to do my sit-ups like Rama.",
    "He has a laundry list of cheese-related credentials.",
    "Which Heine Brothers has the best pastry and drinks? Each week is a new location, because every week they HAVE a new location!",
    "Hey, that lady at Circle K finally shaved her beard.",
    "Oh, dontcha hate it when your baby... poops in your hand...",  
    "It's very easy to descend into the mouth of madness.",
    "It's okay, life ends in sadness.",
    "My roommate used to watch me sleep, but i don't think he was in love with me. I think he wanted me dead. He just stayed up all night listening to Drake and playing Call of Duty and watching Blue Mountain State. He was also HIGHLY addicted to amphetamines. He was always taking Vyvanse and things he bought at herb shops. He looked like a shark. He had an Illuminati sleeve...he like hardcore believed in the Illuminati.",
    "I don't jam much.",
    "And what do you use the tape for...?",
    "Ass Attack",
    "All I wanted to do was cry, but the Lasik I had eliminated my tear ducts.",
    "I wouldn't ask Jimmy Carter to make me an apple pie.",
    "'There's only one letter between me and Mixed Martial Arts'-Emma",
    "It has enough caffeine to make sloths run.",
    "He had so many fingers in so many things.",
    "So... doorknobs on a stick! And then, lots of them.",
    "Satan's Garbage Tree.",
    "Pro-TEIN!",
    "Conclusion: I slapped the shit out of him. Humans cannot survive whale beatings.",
    "Heeeeyyyy how's that butt cable!?",
    "'I'm going to have my leg replaced.' 'You should request the kick-strength of an ostrich.'",
    "Business model: haberdashery/hatchery. Fine, well-dressed eggs.",
    "When I have beer everything is funnier.",
    "'YAAASSSSSSS' 'What?' 'I dont know but this is going to be the best thing EVER.'",
    "Blueberries from the store? They're just bitter little bitches.",
    "That fork was really close to your brain.",
    "Too bad it's not a 'ta-da' list, because then it would be a list of all the magic tricks I can do. It would consist of 1. stealing someone's nose, 2. stealing part of my own thumb.",
    "I don't know, I've never had my throat removed.",
    "'Did anyone do anything fun last night?' 'My friend Jasmine threw up in a sink.'",
    "Constance Whiplash, Snidely Whiplash's estranged wife.",
    "Cottage Cheese in my nethers.",
    "Boom! Say goodbye to your coccyx.",   
    "Hot Fart",
    "That smells like a plate of hot onion gas.",
    "Hot fart six ways to Sunday.",
    "Yeah. Hey, where's my shiv?",
    "A fork is just an open-ended slotted spoon.",
    "'Whats a surreal dream for a blind person?' 'Like if you were just, talking to a caterpillar'",
    "I have-a become a chinese-a stereotype-a",
    "I hate it when you get the poop-sweats.",
    "No more talking dentistry at work. I had a dream that pulled 3 of my own teeth out and they turned out to be pistachios.",
    "Rice pudding! this rice pudding is my baby.",
    "May your flavor pustules always be bulbous.",
    "Sub WHooooofer",
    "Did I tell you about Yolanda Squatpump?",
    "Berb Shnerp! Beel Ferker.",
    "I wouldn't fist a cow.",
    "I jaunt like a mutha fucka.",
    "New York Necks",
    "Jolly Mangina",
    "What if it were pronounced 'pew-cket sqwarrrrr'?",
    "I want nothing but toothpaste and lawn clippings.",
    "'Traffic on I-71 is backed all the way up to the Snyder.' 'I'll back YOU all the way up to the Snyder!'",
    "That's not a shopping cart, that's his WIFE.",
    "I AM the loading dock. Unload into me.",
    "My ass is covered in warts.",
    "Ms. Kenya Bush-Bags",
    "Lauren Bush-Bags McGee",
    "This is my grandfather, Puddin' McGee.",
    "I cant find the main poop but I found two shards.",
    "Mama didn't raise no flute mouth.",
    "Is there any point to anything, Mardi Love?",
    "'Vomit in a bucket, call it 'potpourri.'' 'Was that a Lil' Wayne lyric?'",
    "Brittany McCheese, daughter of Mayor McCheese!",
    "Man smells like a lady da da da da da da da!",
    "St. Fiddle-Faddle Academy",
    "This is the South Biscuit.",
    "The alternates will not poopulate at all!",
    "'What did you do to your hand?' 'I slammed it in 'Diversity Dilemma.''",
    "Gluten-free? Nah I don't play that shit.",
    "Crockpot full of dicks.",
    "Hello Kitty my old friend...",
    "Swiss chard lap band",
    "Al J's Gout House",
    "John Hind-Kick",
    "Snuffle-monkeys. I think I was trying to say sniffle-pumpkins. No, shnookums.",
    "If you're not watching Little Women in surround sound, then you're not watching it.",
    "Meryl Streep is a national treasure.", 
    "Yer a wizard, Cheryl.",
    "These people are a bunch of balogna-ass idiots.",
    "How's Rubbermaid?",
    "I never go anywhere without a Tupperware container. I wear it on my face like a feedbag.",
    "Ohio SUFFERED. 1865! Never forget the wrath of Ohio!!",
    "MODeeznuts",
    "It's not that I like you or anything! I'm just doing it because it's my duty as class rep!",
    "I was just thinking about how much of lightsaber fighting is predicated on the mutual trust that neither party will turn OFF their lightsaber.",
    "Their first name is... their first name... is... it is 'Pumpkin.'",
    "Did you know that the dire wolf is about the same length as a regular wolf, but it weighs 25 times more and it grants wishes.",
    "Yeah. Humps on Legs...LLC.",
    "Luchadorable", 
    "Vape, vape, vape senora, vape it all the time!",
    "If you have a bad enough kidney infection, you could lose your FACE.",
    "'I have a $3.00 credit on VUDU.' 'I didn't know the gods worked that way!'",
    "I am amazed by how many people just... keep living.",
    "How does Digimon only have 3.5 stars?! I swear I will slap somebody.",
    "We shall not speak of The Speculum Incident.",
    "Every time I blink I see Lincoln.",
    "You high as hell!",
    "Death Starry, Starry Night",
    "Puccini!!!",
    "Captain... Are you... Okay?",
    "What do you think about the word 'crankle'?",
    "Meat Bowls",
    "Captain Shift Captain! Shift Captain, My Captain!",
    "Wanna go home and watch 'Alien?' He loves that movie.",
    "Her name is 'Sigourney Weaver.' I just can't imagine someone walking up and saying 'hey Sigourney.'",
    "It's not a combover! It's a comb-up-and-over!",
    "Are you an idiot lady?",
    "It feels like I'm eating swamp things.",
    "You have a face that's perfect for self-checkout machines.",
    "'Hey! Do you remember me?' 'Professor Jasmine Farrier!!' 'Nope!'",
    "Are ya comfortable there?! Cus you look like a PUDDIN!!!!",
    "Jesus! Thus ended Link's adventure.",
    "I have got QUITE the doozy coming down the line.",
    "You some Lon Lon Ranch-lookin mutha fuckas.",
    "How many bees does it take to make honey? Eight. Eight bees.",
    "Do you think a cat girl would retain the flexibility of a cat?",
    "Tore up and skinnnneeeeey.",
    "King cake, it's just a danish with a baby in it!",
    "I always FAIL.",
    "'I'm just a lazy butthole.' '...that sounds like a condition that warrants a diaper.'",
    "Long and thin, his member fluttered about her face.",
    "Yeah if it's just a mushy ball of green that serves no purpose, I ain't about that shit.",
    "Good luck, Suck.",
    "Haha, dolla dolla bill y'allll! I wish I knew what I was talking about.",
    "It took me like 40 minutes to peel the exoskeletons off.",
    "I'm going to call it 'Dark Jungle Novella' so I don't get sued. Jungle Pamphlet.",
    "You are the wind between my knees...",
    "Fifty years of CROTCH",
    "Well I get nervous you're just gonna poop in a garbage can!",
    "I'll have a genie and tunic, please.",
    "Now, chewable Opi-Yums!",
    "We've cross bred Cam Newton with American Pharaoh.",
    "American Ferret",
    "Bring me a thumb drive worthy of Mordor!",
    "How do I bowl? WITH ARMS WIDE OPENNNNN!!",
    "Welcome to the Thrash Hole!!",
    "Watch out fo the laaaaser wall!",
    "Oh, yeah. My Bluetooth seems to be picking up someone else's phone and I can hear waves crashing.",
    "Get that sex worker back!",
    "Tofu turd!",
    "It's days like this I need a Yup.",
    "It's a Casino-themed law school dance.",
    "I built this Death Star here... by the way if you drop a penny in this exhaust pipe it blows up.",
    "I smell like a girdle.",
    "Well, I'm no Carol Channing.",
    "Knitting is my kryptonite.",
    "Awwwwwwww Snape.",
    "Coconut is a drupe.",
    "Every time I go in the men's room I hear Toph and Ryan having some random-ass conversation like, '...yeah, I think fairies could do that...'",
    "That name sounds familiar... I feel like... I think I ding'd her.",
    "My daddy always said, 'when in doubt, just proceed as if she'd said yes!'",
    "Consent...consent is a very important thing.",
    "'Have you ever cried during a movie?' 'I started to get a little choked up in Star Wars Episode 3.'",
    "I was trying to network and I ran into this guy and went to ask him what his name was and what he did but then I realized he was the waiter so I just walked awkwardly ahead of him.",
    "Sausage me.",
    "Coordinators always ride single-file to hide their numbers.",
    "If a sundae in America were called 'super-mega' it would come out in a bathtub.",
    "Should I use some dark magic to make more coffee?",
    "You fought a confederate soldier?",
    "...there's nobody behind that pole right?",
    "Rita isn't short for 'Ritalda'...?",
    "Is your mom an...eagle?",
    "The study of cows...that's called... 'Cattling?'",
    "They're nice separately but together... No. It's like eating a cheese and chocolate sandwich.",
    "I'm not morally opposed to tea lights.",
    "What would you do with a Klondike bar.",
    "I hurt my niece.",
    "Diarrhea of a Wimpy Kid",
    "It's a fun game we're playing. It's called 'if I see your fucking face I'm going to tear it off.'",
    "I don't bandy about the word 'titular' for fun.",
    "Steve the conscious tick.",
    "Speaking of runny dribbles, just listen to my day.",
    "Michael Flatley in 'the Pit'.",
    "You would look so hot in 1816 men's wear.",
    "Buns of Steam",
    "Stop giving me gross things to put in my pocket!",
    "My goth phase ended years ago, I just drop things!",
    "It was like trying to get a beach towel in a coin slot.",
    "Haha hehe...don't mind my bed pan.",
    "Bag full of oniooooons",
    "Outrageous Chemical Pixie Dust",
    "What do you wish of me?? I am but a lowly phone goblin!",
    "Penis okay?",
    "Captain Plaid Beard",
    "He turned the bread into wine, turn the wine into fish! Put it all together it's my favorite dish!",
    "I'm glad I settled on kabob.",
    "I want you to burp me.",
    "Well in Kenya there was a cheetah with the spirit of an ostrich...",
    "Serve a cup of MADNESS", 
    "It's probably a really buff roach.",
    "That's a hat for a tinyyyy sultan.", 
    "I only skate alone!",
    "That's how I like my fingers: balled.",
    "I'm having a brain...stem.",
    "'It just really hurts to bend over right now.' 'I'll bend YOU over ...bend you over till you're screaming in pain. Till we have to rush you to the emergency room!'",
    "I guess today is dab day. Thirty minutes of dabbing.",
    "Yes I'm here to see Dr. Frankenbobble.",
    "He got rammed out of existence.",
    "How is your head still attached?",
    "Did you know a djinn is coming out of your door?",
    "I have a cyst the size of a snow globe.",
    "Hi is this...is this...P-Precious?",
    "Are those dried leaves?",
    "Guy Fieri: half boar, half chef.",
    "Aw yeaaah, extra dangly duck sauce.",
    "Riki Tiki Taxi?",
    "Oh yeah, whenever they're lifting weights and they poop out their insides?",
    "Added a nanny. Add a nanny. Added a nanny.",
    "'Would you ever name your kids Parsley, Sage, Rosemary, and Time?' 'Well no because then my kids would be Parsley Sage, Rosemary Sage, Sage Sage, and Thyme Sage.'",
    "When you release tofu from a tofu press it says 'they never even asked me any questions'.",
    "Sally Struthers. Now that's a name I've not heard in a long time. A long time.",
    "Can I use your buns to make a cock meat sandwich?",
    "Edward Hole Punch Hands",
    "Ring Worm: spreads nice and easy, like Country Crock.",
    "'Does that say blind people taste test? Ew, why would you cook salmon in dishwater?' '...are your eyes alright?'",
    "'What's her name?' 'Tonya Trombone.'",
    "Your head looks like a target. You should feel it! It feels like a horse's nose.",
    "Are you Force-sensitive enough to wield a smooth lightsaber?",
    "He's really cool with being snapped.",
    "Pineapple Ring Eyes",
    "Boom. You just got Forced.",
    "Her suit of armor is made of one giant spoon.",
    "Spank the Maker!",
    "Old Chris Kenobi",
    "Luke gave me very specific instructions not to turn back on until Han Solo was DEAD.",
    "Get your FAT lips out of my face.",
    "Kylo Skylo",
    "Great Chewie, you parked too close and now Luke won't come out of his cave for anything.",
    "It was supposed to be fish, but it was more like a shingle dipped in batter.",
    "I was born in a small tube!",
    "'Do I smell like a grill?' 'I dunno, you smell more like a damp towel.'",
    "Thanks for listening to 91.9, that was the Red Hot Chili Peppers. Next up: in 1969 they released their only song, they're my neighbors!",
    "It's the DONGLE.",
    "Yeah, don't make a movie called 'Forbidden Magic Hidden Thing.' Call it like 'Hot Girl In Asia!' or 'Here Comes The WHALE.'",
    "'Clump it and dump it' that's my cat litter slogan.",
    "Yes, if you are a child, which, none of you are...",
    "Welcome to Adolf Furtwangler's House of Fun!!!!!!!! We have all ze candy and bounzee hausez!",
    "All the people in our department crack me up. In really small innocent ways. Or really vulgar ways.",
    "Belinda?!",
    "Hallo Property Care, I have a question for you, Property Claire!", 
    "Someone's had a big gobby in the Happy Climber.",
    "There's a nun in the building.",
    "The Phantom Menace: it's like watching people drown.",
    "Dinosaurs methane farts burps global warming environment science flatulence",
    "Ddddddd is for Darth",
    "My beak! My beeeeeakkkkkk!!!!",
    "Count Dookie, am I right?",
    "That nasty old witch down at Atlantic No. 5 made Cafe Geneva go out of business.",
    "You know what makes my baby feel at ease? Hangers.",
    "Jesus wore Adidas cleats. You stab me I'll stab you son!",
    "I have that chocolate milk taste in my haunches. I meant jowls!",
    "Oh let me just crawl into this bucket and call the Science Center.",
    "Sconces, aaaahhaaahaaaaaa!!",
    "Speak softly and carry a big stick. Like this 'hello... ima git ya with my stick...'",
    "Tong John Silversmith",
    "Welcome to our garage sale. The theme is 'An Evening in Venice.'",
    "My nerm is derth merl!!",
    "The ansa is blewin in the weeeend.",
    "Get the FUCK out of the way, Fish Face!!!!",
    "It swims ashore; rampage ensues.",
    "She's the Ghenghis Khan of modern day music.",
    "I ate a Breakfast Bondage Burger.",
    "Your stuff is on I-64. I left it by the exit ramp.",
    "And Hades is all like, 'look at this Ima set you on fire. And Ima give you allergies, because that's how I roll.'",
    "Playdates will be on the third Thursday after the harvest.",
    "I ain't about gale-force winds throwing jellyfish in my face.",
    "'What was your favorite part of today?' 'Um, the aquarium? No, no, when I pooped.'",
    "'Whats the difference between a fantasy pirate and a real pirate, in your mind?' 'Scurvy.'",
    "Performance Review: You can perform basic functions.",
    "I found a picture of Mark Twain in Tesla's lap.",
    "When life gives you lemurs...",
    "When life gives you lemons you make soup to nuts.",
    "You need some non-milk naan.",
    "Overall... Overalls. To prevent dress code violations you must wear overalls.",
    "We isn't in Kansas anymore.",
    "Where did my reflection go?",
    "You tend to pick up things.",
    "One main vagina and two side vaginas.",
    "If you wanna hang out, hang out!",
    "I'm not just gonna wander through the building looking for abused women and pizza.",
    "Admittedly, I'm probably the largest ma'am they've ever met.",
    "What kind of animal would I like to be? That's hard. At first you wanna say dolphin, because they're cute, but then they rape sometimes. I don't wanna do that. I think a cat. They seem to have it all figured out. Like, sometimes they just want to knock things off a counter. They're very task-driven.",
    "Being a vegetarian should be easy! You just think 'oh, I have to avoid meat.' But no! Guess what? Your popcorn is covered in cow hooves.",
    "'I like when you spoon me!' 'Oh, I'll spoon your brains out.'",
    "There seems to be a barcode in my grits.",
    "She has Class 5 PMS.",
    "Necrophilia and cryptozoology... She REALLY likes Sasquatch. Now we know why we can't ever find him. She keeps stealing the bodies!",
    "Milton Berle didn't die, he went into witness protection. Because his jokes slayed too many people",
    "Hold your wee for a week!",
    "Squash dishes!!",
    "What a buncha rude soups.",
    "12-foot ninja dinosaur pileup.",
    "Please use the elevator to your rear.",
    "If you get caught in the stairwell, stick it up your ass!",
    "I always feel like somebody's mocking meee.",
    "ChumbaWumba!! I've never seen something so crazy!!!!",
    "Butterfly clips. Like chip clips for butterfly wings. 'Where are you gonna go now? Nowhere!!'",
    "Overly-casual Fridays.",
    "'I should probably see We the People.' 'Seaweed the people?!'",
    "I work at Blockbuster. I meant to order a pizza but now I own four franchises. And a two-liter!",
    "I want doodle pants!!",
    "'I still really want Tesla socks.' 'Tesla's socks? They're more rare than the Shroud of Turin.'",
    "Why do I sing? Doctor can you heeelp meeeeeee?",
    "The Pope is really 3 toddlers stacked on top of one another.",
    "Life would be so hard if our reproductive organs were on our shoulders.",
    "Guy Fieri's Smockhouse: Apron Emporium",
    "Touché my three-headed friend... In ref: dangling participle.",
    "It's my odd attempt at a British Pub. We're going down to the 'Leg, Arm, and Scarf.'",
    "Do you think this guy's name is really Stock Longhurst?",
    "'We'll be doing real smoke with apple and hickory because we know that is a Kentucky thing. There's a lot of hickory around here, but it'll have a little bit of my funk in there.'-actual Guy Fieri quotation",
    "We've not had an info booth in the lobby since, oh, before you were born.",
    "Did you just eat something citrus, Cutie Pie?",
    "'Was he really in a car plane crash?' 'Yes. It was devastating.'",
    "May all your herbs be pharmaceutical-quality.",
    "Condemnation. Is that when the whole country is practicing safe sex?", 
    "Tampa gave birth to the Cuban sandwich.",
    "Remember that time we were gonna put a poo in the theater lobby?",
    "WHO is PP??!",
    "'Choo Choo SWAT Team!' 'Isn't that an anime?!'",
    "'You should get frosted tips for your birthday!' 'Is that a stripper?'",
    "'Ah memories.' 'Mammaries?'", 
    "That was the camping trip where Alice showed us the scars from her breast reduction.",
    "Dear Diary, today I ate a thousand carbs and now my tummy hurts. Love, Maddie",
    "Good job, Tupac!",
    "Look at this phonograph! Every time I do it makes me laugh.",
    "Captain Neckbeard. The most hipster of pirates.",
    "Co...ho...tays. Cohones? Coyotes. Quixotes?",
    "Do Silence!",
    "Legend of Zelda: Precipice of Existence",
    "You know, if I were a stripper I think I'd be really irritated if my boyfriend expected a lap dance every time I got home.",   
    "That's her nickname. Titty Pants.",
    "Asians of Shield",
    "I would follow him off a cliff. I mean... I would LEAD him off a cliff.",
    "There's a snake in my vagina!",
    "That's gonna ruin the whole orgy.",
    "Don't worry ima escape into this wheeeeellllllllllllllllllllllllllllll!",
    "Drench me in marinara!",
    "Curse of the Sewer Rabbi",
    "Old Mother Dammit Sat on a Planet",
    "CHANGE ME.....with science!",  
    "Hot Pink Butt",
    "OMG did u see what Wang Xu did last night",
    "I learned everything I know about cooking from Chopped. That's why eeeeveryyything I cook contains Pop-Rocks!",
    "We don't know what happened, we found him face-down in a pile of nickels.", 
    "I have a case of the apple barps.",
    "Fool me once, shame on you. Fool me twice, it's my fault because I should never trust again.", 
    "Limbs Akimbo! That was my nickname in high school.",
    "If you have garbage on your table... EAT IT.",
    "Spackle me",
    "Shackle me",
    "Sparkle me",
    "Speckle me",
    "The rarest of all reptiles: the Kimono Dragon",
    "I get easily distracted. Gravel!",
    "'Where do you start puzzles?' 'Um... the edges.'",
    "KPop! Hachachacha!",
    "Oreganono",
    "I heard after this she goes crazy for a while.",
    "It's like fire in your hands!!",
    "Comb down and back over. Skunk style.",
    "Actually, there's a wizard.",
    "Wow. I am just not getting love from my fingers today.",
    "'Garden meat.' 'Are you talking about vegetables?'",
    "It's money that's there, that's just kind of hanging out until someone dies.",
    "Yeah she was like, Bizarro Andy.",
    "If I die, delegate all my responsibilities to Andy.",
    "I got a postage stamp right HERE for ya.",
    "Charred white baby. Wait. That came out so wrong.",
    "End of life auction.",
    "Yeah, and if you round up to the nearest thirty, you're thirty.",
    "The hand was smashed in the Spine Spinner!",
    "Wait... you watch DuBBED??!",
    "Would you put your knee down? Would you eat your own knee??!",
    "'Good Lock' - David Lock",
    "Get clucked.",
    "Do you want to work in a fun, friendly, Hunger Games-like atmosphere?",
    "What was that one called? 'Batman Uncorked?'",
    "My children’s book: 'If the Exorcist Took Epicec.'",
    "I’m not putting anything in anyone’s buttock.",
    "Would you be grateful if I let you suck my tongue",
    "Oh you’re VEGAN. We have SPECIAL food for you. In the back.",
    "Lemon.Tart@louisvilleky.gov", 
    "Your knees are smooth.",
    "What’s an 'Ip Man'",
    "'How do you stay warm camping in the winter?' 'You need a big, thick, uh, dick.'",
    "Have you ever gilded anything?",
    "Lots of bathroom hubblub today.",
    "The floor is made of recycled Tigers.",
    "I’ve always wanted to be shot.",
    "I fell asleep to Luke Cage and then I had a dream that I started #BlackLiveMatter.",
    "That’s just a coincidental bell.",
    "Remember that time you bought a book? We bought you a library!",
    "It’s a LAZER HOUSE. It’s very protective.",
    "No one wants pulp in the spigot.",
    "I feel like I’m being cooked from the outside in.",
    "I know that you have an actual medical problem. But you have to remember that I don’t have that problem.",
    "Who put cocaine on my desk?",
    "Anyway that’s lame. They should have a lion named like, Jeff.",
    "I never use tissues. When I have to blow my nose it’s like 'this is a job for Brawny.'",
    "Goodbye forever, Wiz Khalifa.",
    "Just one guy driving a... corn tractor...'", 
    "I have Twix up my sleeves...",
    "He’s like, a really sexy goat.",
    "That kid was sinister as fuck.",
    "Trump is like a mound of dough.", 
    "You’ll never know love until you give birth to a fur human.",
    "'Why would you make jewelry out of your breastmilk?' 'How else are you going to remember that you had a child?'",
    "Cold? Maybe you’re just weak and sick.",
    "Aye, Mucus!",
    "I DON’T SPEAK YER LANGUAGE",
    "I had a dream I saw Phil Collins in a Costco.", 
    "You can treat fart pain.", 
    "'Do you like coffee Cody?' 'No.' 'Cool.'",
    "Bats are the dogs of the air.",
    "National Yams on the Half Shell Day",
    "Digital black face.",
    "It’s like a buttery fog.",
    "She looked like a fabulous witch!",
    "Thai food fever.",
    "I think you like, blinded my third eye.",
    "Tarts In A Misty Garden",
    "ThunderDorfs",
    "I’ve broken my custard. What can I do about that?",
    "Melissa, I believe you have a new face?",
    "My house smells like balls.",
    "That drink is made of alcohol, watermelon jolly ranchers, and black stuff from the oven.", 
    "Yeah they race ghosts. I mean 'goats.'",
    "It’s an 'exorcise bike.' The faster you pedal the faster the spirits leave your body.",
    "I have HUGE tentacles all over that organization.",
    "You need to lower your bread pleasure.",
    "'Phat Wisdom' is my rap name.",
    "My mom has thick legs and balls for feet!",
    "Then he pulled out a vape and ripped some sick cotton.",
    "I looked into my heart and all I found was blood and gristle.", 
    "I have heart gristle from yeeeears of margarine abuse.",
    "I'm gonna pour lavender oil all over your salty bod.",
    "You won’t catch Lindsey Mango working without wearing all six of her blazers.",
    "I've always thought the Jolly Green Giant was attractive.", 
    "Write drunk, edit sober.",
    "Looks like your noodle bowl loosened up!",
    "'Joseph what’s your middle name?' 'Ann Richards!!'",
    "I did it for you. I did it for us.",
    "I’m looking forward to killing your grandchild with a battery.",
    "I'd hate to have a screaming orgasm right in the middle of my day.",
    "I don’t like ham juice that's leaked onto the bottom of the refrigerator. Now, in a CUP...",
    "The Lamb Before Time",
    "Every post is like “yeah, Harambe would have liked to meet that hippo.",
    "I ain’t no 'Amanda Two-Strains'.",
    "It’s a dangling, foamy experience.", 
    "Stupid dogs and their lumps. Their lovely doggy lumps.",
    "This isnt 'Girl, Interrupted' or something, they’re just crackers.",
    "Wheeeen theeeeee sun hits your eye and it makes you go blind, that’s a issue!",
    "Mick Jagger looks like a living mummy made of beef jerky, but somehow still sexy.",
    "People gon’ CHAFE.",
    "That's a funny saying isn't it? 'Keep an eye on it.' Okay like, I'm not a chameleon. I mean it's kind of like a ‘both or nothing’ kind of thing. It's not like I can read manga with one eye and watch this with the other.",
    "I had this cat I thought was really cool and relaxed and just liked to be carried around and put in baby clothes but it turns out it had leukemia and it was like, on its death bed.",
    "You know what would help that park? If they legalized marijuana. Know what else? If they legalized rape. If they taxed every rape? National debt GOOD-BYE.", 
    "I went vegan cold Tofurkey.",
    "I THINK he was a particle.", 
    "Do you not see this cat nuzzling what looks like a super thick dick?",
    "Chicken Pop Punk",
    "There's this guy named Vick who runs a bike shop we could talk to. I have heard that Vick is an alcoholic so it's best to catch him earlier in the day... and he was caught peeping in the ladies room.",
    "Charles Blurbage invented marketing.",
    "Step into the skin mask of an astronaut.",
    "Step onto the surface of an astronaut.",  
    "Gah she shot me in the soul patch.",
    "Sometimes I just do a fat bump of panko bread crumbs.",
    "Also I was wearing… khaki… knee… shorts.",
    "They were totally lost until they found some rando's log cabin.",
    "Is that the trip where everyone was trying to pigeon hole you into doing group stuff and you were like 'nah brah'.", 
    "You made my brain stem tingle!!",
    "It's a bulbous swamp nodule.",
    "Hams on a stick. That's exactly what I feel like!",
    "No Grackle!!",
    "I was robbed. He was going to be the most fabulous bat in Kentuckiana!",
    "'You still shop at the mega Kroger?' 'Excuse me did you say MAGGOT Kroger?'",
    "Oh Chris Farley. He lives in a casket down by the river.",
    "Dinosaur... bone... head. Or... 'skull'.",
    "I would continue to use the ghost van.",
    "Your lovely gundam lumps.",
    "Sarcostic. It's when you say something sarcastic that hurts a lot.",
    "I’ve been in closest that people don't know exist.",
    "We put all our eggs in totality boxes.",
    "The town is nice but the people there are ugly. We have a lot of pollution.", 
    "I draw the line at decorative bacon.",
    "Your brain is like, 100% water.",
    "So the correct question is 'how wide is your roll?'",
    "I remember thinking '...woah.'",
    "Our retail director is the president of the Midwest",
    "She has dumps like a dump. Dump. Dump.",
    "'One guy got stabbed in the neck by a fish.' 'Who gives fish KNIVES?!'",
    "My diet? Out the airlock!",
    "She died because she was on the way to a dance... and she got a bad case of boogie fever.",
    "You have to take a drink every time they switch meeting rooms.",
    "Wow Strike and Spare is pops.",
    "You can service somebody straight out the door.",
    "Bolivian Crumpetpants",
    "Oh. Oh hell yeh. Hell yeh! Hell yeh!",
    "Well do you know what pi squared is? It's a poptart.",
    "Dr. GRUB and the Hagfish",
    "So I start heading up the stairs and I hear them spoons goin'",
    "Hobbiton: where our weed is dank but our holes are not.",
    "Those parents out there are coddling these little freaks.",
    "My dog is half pitbull, half rock.",
    "Double vailbow!",
    "That one got me right in the knucks.",
    "Nice dad!",
    "Fellas you better watch it, when she wind up she bottom she rips sick clouds.",
    "Double vailbow.",
    "That one got me right in the knucks.",
    "Nice dad!",
    "Pork cheese, brewed from pork milk.",
    "Fuck, marry, kill: clown, robot, sultan.",
    "We're trading knuck shots.",
    "I would buy Joe Biden's fart.",
    "Who the HELL is eating the Almond Joys?!",
    "I got deep grooves.",
    "'paste' isn't supported by my web browser.",
    "I don't have hot water. I can't even shave my legs because I'll cut my goosebumps off.",
    "Neither rain nor sleet can touch my feet.",
    "My favorite holiday game is 'how many pipe cleaners can I shove in this reindeer'?",
    "The Platonic Salads",
    "I don't touch the thermostat during the Winter because I don't want you to hollow me out like a taun taun.",
    "Manic Fluff",
    "I don't like her bones.",
    "Hubby button!",
    "Texarkana. It's like Wizard Texas.",
    "I was almost born in a Steak 'n' Ale.",
    "Pop a nutmeg. Papa Nutmeg.",
    "In Finland, Papa Nutmeg comes down the chimney and spits fire!",
    "This kombucha here is no joke. I'm about to shit myself.",
    "Simple Plan is cominnnnn' to town!",
    "Do they make furniture memes?",
    "I like to be homeless on weekends.",
]

// Makes the word "index" to be the actual length of the list
document.body.innerHTML = document.body.innerHTML.replace("index", theList.length);

$('#numberSelect input').first().focus();

//captures the number input by the user
$( "#submit" ).on("click", function() {
  //spits out the form value as "chosenNumber=___"
  var value = ( $( '#chosenNumber' ).serialize() );
  //takes var value and removes the "chosenNumber=" portion
  var num = value.substring(value.indexOf( '=' , 0 ) + 1, value.length);
  event.preventDefault();
  document.write( theList[num - 1] );
});

